// This file is auto-generated by @hey-api/openapi-ts

export { getApiTables, getApiTablesByTableIdAvailability, getWeatherForecast, type Options, postApiReservations } from './sdk.gen';
export type { ClientOptions, GetApiTablesByTableIdAvailabilityData, GetApiTablesByTableIdAvailabilityResponses, GetApiTablesData, GetApiTablesResponses, GetWeatherForecastData, GetWeatherForecastResponse, GetWeatherForecastResponses, PostApiReservationsData, PostApiReservationsResponses, ReservationInfo, WeatherForecast } from './types.gen';
