// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiTablesByTableIdAvailabilityData, GetApiTablesByTableIdAvailabilityResponses, GetApiTablesData, GetApiTablesResponses, GetWeatherForecastData, GetWeatherForecastResponses, PostApiReservationsData, PostApiReservationsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const postApiReservations = <ThrowOnError extends boolean = false>(options: Options<PostApiReservationsData, ThrowOnError>): RequestResult<PostApiReservationsResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostApiReservationsResponses, unknown, ThrowOnError>({
    url: '/api/Reservations',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiTables = <ThrowOnError extends boolean = false>(options?: Options<GetApiTablesData, ThrowOnError>): RequestResult<GetApiTablesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetApiTablesResponses, unknown, ThrowOnError>({ url: '/api/Tables', ...options });

export const getApiTablesByTableIdAvailability = <ThrowOnError extends boolean = false>(options: Options<GetApiTablesByTableIdAvailabilityData, ThrowOnError>): RequestResult<GetApiTablesByTableIdAvailabilityResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetApiTablesByTableIdAvailabilityResponses, unknown, ThrowOnError>({ url: '/api/Tables/{tableId}/availability', ...options });

export const getWeatherForecast = <ThrowOnError extends boolean = false>(options?: Options<GetWeatherForecastData, ThrowOnError>): RequestResult<GetWeatherForecastResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetWeatherForecastResponses, unknown, ThrowOnError>({ url: '/WeatherForecast', ...options });
