// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:7078/' | (string & {});
};

export type ReservationInfo = {
    tablesId?: string;
    customerName?: string;
    customerPhone?: string;
    scheduledAt?: string;
    section?: string;
    remindBeforeHour?: boolean;
};

export type WeatherForecast = {
    date?: string;
    temperatureC?: number | string;
    temperatureF?: number | string;
    summary?: null | string;
};

export type PostApiReservationsData = {
    body: ReservationInfo;
    path?: never;
    query?: never;
    url: '/api/Reservations';
};

export type PostApiReservationsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiTablesData = {
    body?: never;
    path?: never;
    query?: {
        scheduledAt?: string;
    };
    url: '/api/Tables';
};

export type GetApiTablesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiTablesByTableIdAvailabilityData = {
    body?: never;
    path: {
        tableId: number | string;
    };
    query?: {
        scheduledAt?: string;
    };
    url: '/api/Tables/{tableId}/availability';
};

export type GetApiTablesByTableIdAvailabilityResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetWeatherForecastData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/WeatherForecast';
};

export type GetWeatherForecastResponses = {
    /**
     * OK
     */
    200: Array<WeatherForecast>;
};

export type GetWeatherForecastResponse = GetWeatherForecastResponses[keyof GetWeatherForecastResponses];
